---
name: build-zephyr
description: Build a Zephyr based EC firmware
inputs:
  target:
    description: target
    default: lotus
runs:
  using: composite
  defaults:
    run:
      working-directory: /data/ec_home/chromiumos
  steps:
    - name: Build Lotus
      run: |
        cros_sdk zmake build ${{ inputs.target }}
        echo Built ${{ inputs.target }} EC

    - name: File sha256
      run: sha256sum src/platform/ec/build/zephyr/${{ inputs.target }}/output/ec.bin

    - name: Generate artifact version
      run: |
        echo "VERSIONINFO=$(date -u +'%Y-%m-%d-%H-%M-%S')_$GITHUB_SHA" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.target }}.${{ env.VERSIONINFO }}
        path: src/platform/ec/build/zephyr/${{ inputs.target }}/output
