name: build lotus, azalea firmware

on:
  push:
    branches:
      - lotus*
  pull_request:
    branches:
      - lotus-zephyr
  workflow_dispatch:

jobs:
  build:
    name: Build lotus/azalea
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: /data/ec_home/chromiumos

    steps:
      # TODO: Might need to use git?
      #- name: Checkout EC code
      #  uses: actions/checkout@v3
      #  with:
      #    path: /data/ec_home/chromiumos/src/platform/ec

      #- name: Checkout Zephyr code
      #  uses: actions/checkout@v2
      #    path: /data/ec_home/chromiumos/src/third_party/zephyr/main
      #    ref: lotus-zephyr
      #    repository: ssh://git@github.com/FrameworkComputer/zephyr-ec

      # Need to manually checkout
      # Error: Repository path '/data/ec_home/chromiumos/src/platform/ec' is not under '/data/ec_home/actions-runner/_work/ec/ec'
      # See: https://github.com/actions/checkout/issues/197
      - name: Manual checkout
        run: |
          pushd src/platform/ec
          git fetch github-private
          git clean -ffdx
          git reset --hard github-private/$GITHUB_REF_NAME
          popd

          pushd src/third_party/zephyr/main
          git fetch github-private
          git clean -ffdx
          git reset --hard github-private/lotus-zephyr
          popd

      - uses: ./.github/workflows/build-zephyr.yml
        with:
          target: lotus

      #- uses: ./.github/workflows/build-zephyr
      #  with:
      #    target: azalea
