name: build lotus, azalea firmware

on:
  push:
    branches:
      - lotus*
  pull_request:
    branches:
      - lotus-zephyr
  workflow_dispatch:

jobs:
  build:
    name: Build lotus/azalea
    runs-on: [self-hosted]

    steps:
      # TODO: Might need to use git?
      - name: Checkout EC code
        uses: actions/checkout@v2
          path: /data/ec_home/chromiumos/src/platform/ec

      #- name: Checkout Zephyr code
      #  uses: actions/checkout@v2
      #    path: /data/ec_home/chromiumos/src/third_party/zephyr/main
      #    ref: lotus-zephyr
      #    repository: ssh://git@github.com/FrameworkComputer/zephyr-ec

          # pushd src/platform/ec
          # git fetch github-private
          # git clean -ffdx
          # git reset --hard $GITHUB_REF
          # popd
      - name: Manual checkout
        run: |
          pushd ~/chromiumos
          pushd src/third_party/zephyr/main
          git fetch github-private
          git clean -ffdx
          git reset --hard lotus-zephyr
          popd

      - uses: ./.github/workflows/build-zephyr
        with:
          target: lotus

      #- uses: ./.github/workflows/build-zephyr
      #  with:
      #    target: azalea
